name: Publish Package to NPM
on:
    push:
        tags:
            - "v*.*.*"
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: node-setup
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"
            - name: build
              run: |
                  npm ci
                  npm run build-lib
                  cp ./src/lib/_styles.css ./dist/lib/_styles.css
            - name: publish
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
