name: Publish Package to NPM
on:
    push:
        tags:
            - "v*.*.*"
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Build
              run: |
                  npm ci
                  npm run build-lib
                  cp ./src/lib/utils/_styles.css ./dist/lib/utils/_styles.css

            - name: Publish
              run: npm publish --provenance --access public
