name: Deploy Demo to GitHub Pages
on:
    push:
        branches:
            - main
permissions:
    contents: write
    pages: write
    id-token: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: node-setup
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
                  registry-url: "https://registry.npmjs.org"

            - name: build
              run: |
                  npm ci
                  npm run build-lib
                  cp ./src/lib/utils/_styles.css ./dist/lib/utils/_styles.css
                  npm run build-demo
                  #
                  mkdir -p deploy
                  cp -r dist/demo/* deploy/

            - name: deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./deploy
                  publish_branch: gh-pages
                  force_orphan: true
